[server]
port=9002 # Server port
html_root="frontend/dist/" # HTML files to be hosted
otherusers=1 # Send where other users are listening, 0 to disable
threads=2

[websdr]
register_online=false # If the SDR should be registered on https://sdr-list.xyz then put it to true
name="Name" # Name that is shown on https://sdr-list.xyz
antenna="Whip" # Antenna that is shown on https://sdr-list.xyz
grid_locator="QTH Locator" # 4 or 6 length Grid Locatlr shown on https://sdr-list.xyz and for the Distance of FT8 Signals
hostname="your IP, or ddns, or no-ip" # If you use ddns or something to host with a domain enter it here for https://sdr-list.xyzv

[limits]
audio=100
waterfall=100
events=100

[input]
sps=60000000 # Input Sample Rate
fft_size=8388608 # FFT bins alt. 1048576, 2097152, 4194304, 8388608 (default), 16777216, look at https://www.mymathtables.com/numbers/power-exponentiation/power-of-2.html
fft_threads=2
brightness_offset=-8 # Waterfall brightness offset. Reduce to negative if you see black regions in the waterfall # brightness_offset=-8 when -g 40 -a 0 -m low
frequency=0 # Baseband frequency
signal="real" # real or iq
accelerator="opencl" # Accelerator: none, cuda, opencl
audio_sps=12000 # Audio Sample Rate
audio_compression="flac" # flac or opus
waterfall_size=1024
waterfall_compression="zstd" # zstd or av1
smeter_offset=7 # smeter_offset=8 when -g 40 -a 0 -m low

[input.driver]
name="stdin" # Driver name
format="s16" # Sample format: u8, s8, u16, s16, u32, s32, f32, f64

[input.defaults]
frequency=7120000 # Default frequency to show user 7120000
modulation="LSB" # Default modulation
