[server]
port=9002 # Server port
html_root="frontend/dist/" # HTML files to be hosted
otherusers=1 # Send where other users are listening, 0 to disable
threads=2

[websdr]
register_online=false # If the SDR should be registered on https://sdr-list.xyz then put it to true
name="Name" # Name that is shown on https://sdr-list.xyz
antenna="Whip" # Antenna that is shown on https://sdr-list.xyz
grid_locator="QTH Locator" # 4 or 6 length Grid Locatlr shown on https://sdr-list.xyz and for the Distance of FT8 Signals
hostname="your IP, or ddns, or no-ip" # If you use ddns or something to host with a domain enter it here for https://sdr-list.xyzv

[input]
sps=1536000 # Input Sample Rate
fft_size=131072 # FFT bins
brightness_offset=-15 # Waterfall brightness offset. Reduce to negative if you see black regions in the waterfall
frequency=1242000 # Baseband frequency
signal="iq" # real or iq
fft_threads=2
accelerator="none" # Accelerator: none, cuda, opencl
audio_sps=12000 # Audio Sample Rate
audio_compression="flac" # flac or opus
smeter_offset=-2
waterfall_size=1024
waterfall_compression="zstd"

[input.driver]
name="stdin" # Driver name
format="u8" # Sample format: u8, s8, u16, s16, u32, s32, f32, f64

[input.defaults]
frequency=1170000 # Default frequency to show user
modulation="AM" # Default modulation
